# ---------------------------
# Datasource
# ---------------------------
spring.datasource.url=${postgressURL}/postgres?prepareThreshold=0
spring.datasource.username=${postgressUsername}
spring.datasource.password=${postgressPassword}

# ---------------------------
# JPA / Hibernate
# ---------------------------
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
